sudo: required
language: cpp
dist: trusty

os:
  - linux

compiler:
  - gcc
  - clang

arch:
  packages:
    - cmake
    - gcc
    - clang

  script:
    - echo $CXX_FOR_BUILD
	- echo $CC_FOR_BUILD
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make -j4

script:
  - echo $CXX_FOR_BUILD
  - echo $CC_FOR_BUILD
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

branches:
  only:
    - master

notifications:
  recipients:
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always

